channels:
  - bioconda
  - anaconda
  - conda-forge
dependencies:
  - picard =2.23.3
  - vcftools =0.1.16
  - bcftools =1.10.2
  - plink2
  - tabix 
  - bioconductor-VariantAnnotation =1.36.0
  - moreutils
  
