channels:
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::python=3.8.5
  - bioconda::picard=2.23.3-0
  - bioconda::vcftools=0.1.16
  - bioconda::bcftools=1.10.2
  - bioconda::plink2=2.00a2.3
  - bioconda::tabix=0.2.6
  - bioconda::bioconductor-VariantAnnotation=1.36.0
  - bioconda::moreutils=0.5.7
